### ISSUE TITLE
mkdir if path the sqlite file does not exist

### ISSUE THREAD

**Issue by meganlkm** [intuitivetechnologygroup/sqlite-formula#6]
state fails when the path to the sqlite file does not exist:

````
----------
          ID: mytable
    Function: sqlite3.table_present
      Result: False
     Comment: unable to open database file
     Started: 16:41:50.368918
    Duration: 0.772 ms
     Changes:
````

**Comment by meganlkm** [comment]
looks like we're trying to create the directory as `db_location` rather than the parent of `db_location`

````
----------
          ID: creates_db_location
    Function: file.directory
        Name: /etc/salt/sdb/tmp.db
      Result: False
     Comment: Specified location /etc/salt/sdb/tmp.db exists and is a file
     Started: 16:58:47.410466
    Duration: 0.699 ms
     Changes:
----------
          ID: tmp
    Function: sqlite3.table_present
      Result: False
     Comment: unable to open database file
     Started: 16:58:47.411664
    Duration: 0.747 ms
     Changes:
````
